name: Postsubmit Checks
on:
  push:
    branches:
      - master

jobs:
  perf:
   name: Performance monitoring (NVGPU)
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v2
       with:
         submodules: 'recursive'
     
     - name: Dump GitHub context
       env:
         PULL_REQUEST_NUMBER: ${{github.event.number}}
         GITHUB_CONTEXT: ${{ toJson(github) }}
       run: echo "$GITHUB_CONTEXT"
